language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y lvm2 liblvm2-dev libdevmapper-dev

install:
  - make deps

script:
  - make
  - make lint