# Copyright 2018-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:

  - label: ":docker: Build"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_BUILDKIT: "1"
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
    command: make docker-images

  - wait

    # Global concurrency has been set to one in the website configuration.
    # With that we can now clean up loop devices before starting jobs to ensure
    # we don't hit the loop device limit
  - label: ":lint-roller: loop device cleanup"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    command: 'sudo losetup -D'

  - wait

  # Git history validation happens after the 'wait' step so it happens
  # in parallel with the subsequent tests and does not prevent them
  # from running in the event of a validation failure.
  - label: 'git log validation'
    command: './.buildkite/logcheck.sh'

  - label: ":hammer: snapshotter tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd snapshotter && make test-docker-unit'

  - label: ":rotating_light: :hammer: snapshotter *root* tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd snapshotter && make test-docker-all'

  - label: ":running_shirt_with_sash: runtime unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd runtime && make test-docker-unit'

  - label: ":rotating_light: :running_shirt_with_sash: runtime isolated tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    artifact_paths:
      - "runtime/logs/*"
    command: 'cd runtime && make test-docker-isolated'

  - label: ":fencer: agent unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd agent && make test-docker-unit'

  - label: ":gear: vm task unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd internal/vm && make test-docker-unit'

  - label: ":exclamation: event tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    command: 'cd eventbridge && make test-docker-unit'
