# Copyright 2018-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:

  - label: ":docker: Build"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-race"
    command:
      - make test-images
      - docker run --rm -v $PWD:/mnt debian:stretch-slim rm -rf /mnt/tools/image-builder/rootfs
      - sudo install -d -o root -g buildkite-agent -m 775 "/local/artifacts/$BUILDKITE_BUILD_NUMBER"
      - cp tools/image-builder/rootfs.img "/local/artifacts/$BUILDKITE_BUILD_NUMBER/"

  - wait

    # Global concurrency has been set to one in the website configuration.
    # With that we can now clean up loop devices before starting jobs to ensure
    # we don't hit the loop device limit
  - label: ":lint-roller: loop device cleanup"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    command: 'sudo losetup -D'
    concurrency: 1
    concurrency_group: 'loop-device test'

  - wait

  # Git history validation happens after the 'wait' step so it happens
  # in parallel with the subsequent tests and does not prevent them
  # from running in the event of a validation failure.
  - label: 'git log validation'
    command: './.buildkite/logcheck.sh'

  - label: ":gear: unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      EXTRAGOARGS: "-v -count=1 -race"
    command:
      - cp "/local/artifacts/$BUILDKITE_BUILD_NUMBER/rootfs.img" tools/image-builder/rootfs.img
      - make test-in-docker
    timeout_in_minutes: 10

  - label: ":rotating_light: :hammer: snapshotter *root* tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1 -race"
    command: 'make -C snapshotter integ-test'
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: 'loop-device test'

  - label: ":rotating_light: :running_shirt_with_sash: runtime isolated tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1 -race"
    artifact_paths:
      - "runtime/logs/*"
    command:
      - make -C runtime integ-test FICD_SNAPSHOTTER=devmapper FICD_DM_POOL=build_${BUILDKITE_BUILD_NUMBER}_runtime
    timeout_in_minutes: 10

  - label: ":rotating_light: :exclamation: example tests (naive)"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    artifact_paths:
      - "examples/logs/*"
    command: 'make -C examples integ-test'
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: 'loop-device test'

  - label: ":rotating_light: :exclamation: example tests (devmapper)"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1"
    artifact_paths:
      - "examples/logs/*"
    command:
      - make -C examples integ-test TEST_SS=devmapper TEST_POOL=build_${BUILDKITE_BUILD_NUMBER}_example
    timeout_in_minutes: 10

  - label: ":rotating_light: :running_shirt_with_sash: runtime isolated tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_IMAGE_TAG: "$BUILDKITE_BUILD_NUMBER"
      EXTRAGOARGS: "-v -count=1 -race"
    artifact_paths:
      - "runtime/logs/*"
    command:
      - make -C runtime integ-test FICD_SNAPSHOTTER=devmapper FICD_DM_POOL=build_${BUILDKITE_BUILD_NUMBER}_runtime_al2 FIRECRACKER_CONTAINERD_TEST_IMAGE=localhost/firecracker-containerd-test-al2
    timeout_in_minutes: 10
