# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:
  - label: ':go: go mod download'
    command: 'go mod download'

  # We use a "wait" step here, because Go's module logic freaks out when
  # multiple go builds are downloading to the same cache.
  - wait

  - label: 'build'
    command: 'make'

  - label: ':hammer: snapshotter tests'
    commands:
      - "cd snapshotter"
      - "DISABLE_ROOT_TESTS='true' make test EXTRAGOARGS='-v -count=1'"

  - label: ':rotating_light: snapshotter *root* tests'
    commands:
      - "cd snapshotter"
      - "sudo make test EXTRAGOARGS='-v -count=1'"
