// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/types.proto

package proto // import "github.com/firecracker-microvm/firecracker-containerd/proto"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/gogo/protobuf/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Message to store bundle/config.json bytes
type ExtraData struct {
	JsonSpec             []byte     `protobuf:"bytes,1,opt,name=JsonSpec,proto3" json:"JsonSpec,omitempty"`
	RuncOptions          *types.Any `protobuf:"bytes,2,opt,name=RuncOptions,proto3" json:"RuncOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ExtraData) Reset()         { *m = ExtraData{} }
func (m *ExtraData) String() string { return proto.CompactTextString(m) }
func (*ExtraData) ProtoMessage()    {}
func (*ExtraData) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{0}
}
func (m *ExtraData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraData.Unmarshal(m, b)
}
func (m *ExtraData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraData.Marshal(b, m, deterministic)
}
func (dst *ExtraData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraData.Merge(dst, src)
}
func (m *ExtraData) XXX_Size() int {
	return xxx_messageInfo_ExtraData.Size(m)
}
func (m *ExtraData) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraData.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraData proto.InternalMessageInfo

func (m *ExtraData) GetJsonSpec() []byte {
	if m != nil {
		return m.JsonSpec
	}
	return nil
}

func (m *ExtraData) GetRuncOptions() *types.Any {
	if m != nil {
		return m.RuncOptions
	}
	return nil
}

// Message to specify the various Firecracker VM configurations for a task
type FirecrackerConfig struct {
	RuncOptions       *types.Any                       `protobuf:"bytes,1,opt,name=RuncOptions,proto3" json:"RuncOptions,omitempty"`
	NetworkInterfaces []*FirecrackerNetworkInterface   `protobuf:"bytes,2,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
	KernelImagePath   string                           `protobuf:"bytes,3,opt,name=KernelImagePath,proto3" json:"KernelImagePath,omitempty"`
	KernelArgs        string                           `protobuf:"bytes,4,opt,name=KernelArgs,proto3" json:"KernelArgs,omitempty"`
	MachineCfg        *FirecrackerMachineConfiguration `protobuf:"bytes,5,opt,name=MachineCfg,proto3" json:"MachineCfg,omitempty"`
	RootDrive         *FirecrackerDrive                `protobuf:"bytes,6,opt,name=RootDrive,proto3" json:"RootDrive,omitempty"`
	// Specifies the additional block device config for the VM. Note that
	// the snapshotter used might itself present block devices to the be
	// attached to the VM. This fields allows additional block devices to
	// that list.
	AdditionalDrives            []*FirecrackerDrive `protobuf:"bytes,7,rep,name=AdditionalDrives,proto3" json:"AdditionalDrives,omitempty"`
	FirecrackerNetworkNamespace string              `protobuf:"bytes,8,opt,name=FirecrackerNetworkNamespace,proto3" json:"FirecrackerNetworkNamespace,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}            `json:"-"`
	XXX_unrecognized            []byte              `json:"-"`
	XXX_sizecache               int32               `json:"-"`
}

func (m *FirecrackerConfig) Reset()         { *m = FirecrackerConfig{} }
func (m *FirecrackerConfig) String() string { return proto.CompactTextString(m) }
func (*FirecrackerConfig) ProtoMessage()    {}
func (*FirecrackerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{1}
}
func (m *FirecrackerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerConfig.Unmarshal(m, b)
}
func (m *FirecrackerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerConfig.Marshal(b, m, deterministic)
}
func (dst *FirecrackerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerConfig.Merge(dst, src)
}
func (m *FirecrackerConfig) XXX_Size() int {
	return xxx_messageInfo_FirecrackerConfig.Size(m)
}
func (m *FirecrackerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerConfig proto.InternalMessageInfo

func (m *FirecrackerConfig) GetRuncOptions() *types.Any {
	if m != nil {
		return m.RuncOptions
	}
	return nil
}

func (m *FirecrackerConfig) GetNetworkInterfaces() []*FirecrackerNetworkInterface {
	if m != nil {
		return m.NetworkInterfaces
	}
	return nil
}

func (m *FirecrackerConfig) GetKernelImagePath() string {
	if m != nil {
		return m.KernelImagePath
	}
	return ""
}

func (m *FirecrackerConfig) GetKernelArgs() string {
	if m != nil {
		return m.KernelArgs
	}
	return ""
}

func (m *FirecrackerConfig) GetMachineCfg() *FirecrackerMachineConfiguration {
	if m != nil {
		return m.MachineCfg
	}
	return nil
}

func (m *FirecrackerConfig) GetRootDrive() *FirecrackerDrive {
	if m != nil {
		return m.RootDrive
	}
	return nil
}

func (m *FirecrackerConfig) GetAdditionalDrives() []*FirecrackerDrive {
	if m != nil {
		return m.AdditionalDrives
	}
	return nil
}

func (m *FirecrackerConfig) GetFirecrackerNetworkNamespace() string {
	if m != nil {
		return m.FirecrackerNetworkNamespace
	}
	return ""
}

// Message to specify network config for a Firecracker VM
type FirecrackerNetworkInterface struct {
	MacAddress           string                  `protobuf:"bytes,1,opt,name=MacAddress,proto3" json:"MacAddress,omitempty"`
	HostDevName          string                  `protobuf:"bytes,2,opt,name=HostDevName,proto3" json:"HostDevName,omitempty"`
	AllowMMDS            bool                    `protobuf:"varint,3,opt,name=AllowMMDS,proto3" json:"AllowMMDS,omitempty"`
	InRateLimiter        *FirecrackerRateLimiter `protobuf:"bytes,4,opt,name=InRateLimiter,proto3" json:"InRateLimiter,omitempty"`
	OutRateLimiter       *FirecrackerRateLimiter `protobuf:"bytes,5,opt,name=OutRateLimiter,proto3" json:"OutRateLimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FirecrackerNetworkInterface) Reset()         { *m = FirecrackerNetworkInterface{} }
func (m *FirecrackerNetworkInterface) String() string { return proto.CompactTextString(m) }
func (*FirecrackerNetworkInterface) ProtoMessage()    {}
func (*FirecrackerNetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{2}
}
func (m *FirecrackerNetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerNetworkInterface.Unmarshal(m, b)
}
func (m *FirecrackerNetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerNetworkInterface.Marshal(b, m, deterministic)
}
func (dst *FirecrackerNetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerNetworkInterface.Merge(dst, src)
}
func (m *FirecrackerNetworkInterface) XXX_Size() int {
	return xxx_messageInfo_FirecrackerNetworkInterface.Size(m)
}
func (m *FirecrackerNetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerNetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerNetworkInterface proto.InternalMessageInfo

func (m *FirecrackerNetworkInterface) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *FirecrackerNetworkInterface) GetHostDevName() string {
	if m != nil {
		return m.HostDevName
	}
	return ""
}

func (m *FirecrackerNetworkInterface) GetAllowMMDS() bool {
	if m != nil {
		return m.AllowMMDS
	}
	return false
}

func (m *FirecrackerNetworkInterface) GetInRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.InRateLimiter
	}
	return nil
}

func (m *FirecrackerNetworkInterface) GetOutRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.OutRateLimiter
	}
	return nil
}

// Message to set the machine config for a Firecracker VM
type FirecrackerMachineConfiguration struct {
	CPUTemplate string `protobuf:"bytes,1,opt,name=CPUTemplate,proto3" json:"CPUTemplate,omitempty"`
	HtEnabled   bool   `protobuf:"varint,2,opt,name=HtEnabled,proto3" json:"HtEnabled,omitempty"`
	// Specifies the memory size of VM
	// This lets us create a Firecracker VM of up to 4096 TiB, which
	// for a mircroVM should be large enough
	MemSizeMib           uint32   `protobuf:"varint,3,opt,name=MemSizeMib,proto3" json:"MemSizeMib,omitempty"`
	VcpuCount            uint32   `protobuf:"varint,4,opt,name=VcpuCount,proto3" json:"VcpuCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerMachineConfiguration) Reset()         { *m = FirecrackerMachineConfiguration{} }
func (m *FirecrackerMachineConfiguration) String() string { return proto.CompactTextString(m) }
func (*FirecrackerMachineConfiguration) ProtoMessage()    {}
func (*FirecrackerMachineConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{3}
}
func (m *FirecrackerMachineConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Unmarshal(m, b)
}
func (m *FirecrackerMachineConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Marshal(b, m, deterministic)
}
func (dst *FirecrackerMachineConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerMachineConfiguration.Merge(dst, src)
}
func (m *FirecrackerMachineConfiguration) XXX_Size() int {
	return xxx_messageInfo_FirecrackerMachineConfiguration.Size(m)
}
func (m *FirecrackerMachineConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerMachineConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerMachineConfiguration proto.InternalMessageInfo

func (m *FirecrackerMachineConfiguration) GetCPUTemplate() string {
	if m != nil {
		return m.CPUTemplate
	}
	return ""
}

func (m *FirecrackerMachineConfiguration) GetHtEnabled() bool {
	if m != nil {
		return m.HtEnabled
	}
	return false
}

func (m *FirecrackerMachineConfiguration) GetMemSizeMib() uint32 {
	if m != nil {
		return m.MemSizeMib
	}
	return 0
}

func (m *FirecrackerMachineConfiguration) GetVcpuCount() uint32 {
	if m != nil {
		return m.VcpuCount
	}
	return 0
}

// Message to specify the block device config for a Firecracker VM
type FirecrackerDrive struct {
	IsReadOnly           bool                    `protobuf:"varint,1,opt,name=IsReadOnly,proto3" json:"IsReadOnly,omitempty"`
	IsRootDevice         bool                    `protobuf:"varint,2,opt,name=IsRootDevice,proto3" json:"IsRootDevice,omitempty"`
	Partuuid             string                  `protobuf:"bytes,3,opt,name=Partuuid,proto3" json:"Partuuid,omitempty"`
	PathOnHost           string                  `protobuf:"bytes,4,opt,name=PathOnHost,proto3" json:"PathOnHost,omitempty"`
	RateLimiter          *FirecrackerRateLimiter `protobuf:"bytes,5,opt,name=RateLimiter,proto3" json:"RateLimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FirecrackerDrive) Reset()         { *m = FirecrackerDrive{} }
func (m *FirecrackerDrive) String() string { return proto.CompactTextString(m) }
func (*FirecrackerDrive) ProtoMessage()    {}
func (*FirecrackerDrive) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{4}
}
func (m *FirecrackerDrive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerDrive.Unmarshal(m, b)
}
func (m *FirecrackerDrive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerDrive.Marshal(b, m, deterministic)
}
func (dst *FirecrackerDrive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerDrive.Merge(dst, src)
}
func (m *FirecrackerDrive) XXX_Size() int {
	return xxx_messageInfo_FirecrackerDrive.Size(m)
}
func (m *FirecrackerDrive) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerDrive.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerDrive proto.InternalMessageInfo

func (m *FirecrackerDrive) GetIsReadOnly() bool {
	if m != nil {
		return m.IsReadOnly
	}
	return false
}

func (m *FirecrackerDrive) GetIsRootDevice() bool {
	if m != nil {
		return m.IsRootDevice
	}
	return false
}

func (m *FirecrackerDrive) GetPartuuid() string {
	if m != nil {
		return m.Partuuid
	}
	return ""
}

func (m *FirecrackerDrive) GetPathOnHost() string {
	if m != nil {
		return m.PathOnHost
	}
	return ""
}

func (m *FirecrackerDrive) GetRateLimiter() *FirecrackerRateLimiter {
	if m != nil {
		return m.RateLimiter
	}
	return nil
}

// Message to specify an IO rate limiter with bytes/s and ops/s limits
type FirecrackerRateLimiter struct {
	Bandwidth            *FirecrackerTokenBucket `protobuf:"bytes,1,opt,name=Bandwidth,proto3" json:"Bandwidth,omitempty"`
	Ops                  *FirecrackerTokenBucket `protobuf:"bytes,2,opt,name=Ops,proto3" json:"Ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FirecrackerRateLimiter) Reset()         { *m = FirecrackerRateLimiter{} }
func (m *FirecrackerRateLimiter) String() string { return proto.CompactTextString(m) }
func (*FirecrackerRateLimiter) ProtoMessage()    {}
func (*FirecrackerRateLimiter) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{5}
}
func (m *FirecrackerRateLimiter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerRateLimiter.Unmarshal(m, b)
}
func (m *FirecrackerRateLimiter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerRateLimiter.Marshal(b, m, deterministic)
}
func (dst *FirecrackerRateLimiter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerRateLimiter.Merge(dst, src)
}
func (m *FirecrackerRateLimiter) XXX_Size() int {
	return xxx_messageInfo_FirecrackerRateLimiter.Size(m)
}
func (m *FirecrackerRateLimiter) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerRateLimiter.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerRateLimiter proto.InternalMessageInfo

func (m *FirecrackerRateLimiter) GetBandwidth() *FirecrackerTokenBucket {
	if m != nil {
		return m.Bandwidth
	}
	return nil
}

func (m *FirecrackerRateLimiter) GetOps() *FirecrackerTokenBucket {
	if m != nil {
		return m.Ops
	}
	return nil
}

// Message to specify a token buicket used to rate limit disk and network IO for a Firecracker VM
type FirecrackerTokenBucket struct {
	OneTimeBurst         int64    `protobuf:"varint,1,opt,name=OneTimeBurst,proto3" json:"OneTimeBurst,omitempty"`
	RefillTime           int64    `protobuf:"varint,2,opt,name=RefillTime,proto3" json:"RefillTime,omitempty"`
	Capacity             int64    `protobuf:"varint,3,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirecrackerTokenBucket) Reset()         { *m = FirecrackerTokenBucket{} }
func (m *FirecrackerTokenBucket) String() string { return proto.CompactTextString(m) }
func (*FirecrackerTokenBucket) ProtoMessage()    {}
func (*FirecrackerTokenBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_8077c43efe66723f, []int{6}
}
func (m *FirecrackerTokenBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirecrackerTokenBucket.Unmarshal(m, b)
}
func (m *FirecrackerTokenBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirecrackerTokenBucket.Marshal(b, m, deterministic)
}
func (dst *FirecrackerTokenBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirecrackerTokenBucket.Merge(dst, src)
}
func (m *FirecrackerTokenBucket) XXX_Size() int {
	return xxx_messageInfo_FirecrackerTokenBucket.Size(m)
}
func (m *FirecrackerTokenBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_FirecrackerTokenBucket.DiscardUnknown(m)
}

var xxx_messageInfo_FirecrackerTokenBucket proto.InternalMessageInfo

func (m *FirecrackerTokenBucket) GetOneTimeBurst() int64 {
	if m != nil {
		return m.OneTimeBurst
	}
	return 0
}

func (m *FirecrackerTokenBucket) GetRefillTime() int64 {
	if m != nil {
		return m.RefillTime
	}
	return 0
}

func (m *FirecrackerTokenBucket) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*ExtraData)(nil), "firecracker.containerd.ExtraData")
	proto.RegisterType((*FirecrackerConfig)(nil), "firecracker.containerd.FirecrackerConfig")
	proto.RegisterType((*FirecrackerNetworkInterface)(nil), "firecracker.containerd.FirecrackerNetworkInterface")
	proto.RegisterType((*FirecrackerMachineConfiguration)(nil), "firecracker.containerd.FirecrackerMachineConfiguration")
	proto.RegisterType((*FirecrackerDrive)(nil), "firecracker.containerd.FirecrackerDrive")
	proto.RegisterType((*FirecrackerRateLimiter)(nil), "firecracker.containerd.FirecrackerRateLimiter")
	proto.RegisterType((*FirecrackerTokenBucket)(nil), "firecracker.containerd.FirecrackerTokenBucket")
}

func init() { proto.RegisterFile("proto/types.proto", fileDescriptor_types_8077c43efe66723f) }

var fileDescriptor_types_8077c43efe66723f = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x75, 0x1b, 0xad, 0xbb, 0xc1, 0x66, 0xa1, 0x29, 0x0c, 0x04, 0x55, 0xae, 0x7a,
	0x43, 0x2a, 0x6d, 0x12, 0x5c, 0x20, 0xa4, 0xf5, 0x63, 0xd3, 0x0a, 0xeb, 0x5a, 0x79, 0x65, 0x48,
	0xdc, 0x20, 0x37, 0x39, 0x6d, 0xad, 0x26, 0x76, 0xe4, 0x38, 0xdd, 0xca, 0xcb, 0x70, 0x8b, 0xc4,
	0x15, 0xef, 0xc4, 0x83, 0x20, 0xbb, 0x1f, 0x49, 0xbb, 0x09, 0x0a, 0x5c, 0xb5, 0xfe, 0xf7, 0x9c,
	0x9f, 0x8f, 0xff, 0xe7, 0xd8, 0x45, 0xfb, 0x91, 0x14, 0x4a, 0x54, 0xd4, 0x24, 0x82, 0xd8, 0x35,
	0xdf, 0xf1, 0x41, 0x9f, 0x49, 0xf0, 0x24, 0xf5, 0x46, 0x20, 0x5d, 0x4f, 0x70, 0x45, 0x19, 0x07,
	0xe9, 0x1f, 0x3e, 0x19, 0x08, 0x31, 0x08, 0xa0, 0x62, 0xa2, 0x7a, 0x49, 0xbf, 0x42, 0xf9, 0x64,
	0x9a, 0xe2, 0x7c, 0x46, 0x85, 0xd3, 0x5b, 0x25, 0x69, 0x83, 0x2a, 0x8a, 0x0f, 0x51, 0xfe, 0x5d,
	0x2c, 0xf8, 0x55, 0x04, 0x9e, 0x6d, 0x95, 0xac, 0xf2, 0x0e, 0x59, 0xac, 0xf1, 0x2b, 0x54, 0x24,
	0x09, 0xf7, 0xda, 0x91, 0x62, 0x82, 0xc7, 0xf6, 0x46, 0xc9, 0x2a, 0x17, 0x8f, 0x1e, 0xbb, 0x53,
	0xb2, 0x3b, 0x27, 0xbb, 0x55, 0x3e, 0x21, 0xd9, 0x40, 0xe7, 0xc7, 0x26, 0xda, 0x3f, 0x4b, 0xcb,
	0xaa, 0x0b, 0xde, 0x67, 0x83, 0x55, 0x9a, 0xb5, 0x26, 0x0d, 0x53, 0xb4, 0x7f, 0x09, 0xea, 0x46,
	0xc8, 0x51, 0x93, 0x2b, 0x90, 0x7d, 0xea, 0x81, 0xae, 0x25, 0x57, 0x2e, 0x1e, 0x1d, 0xbb, 0xf7,
	0x9f, 0xde, 0xcd, 0xec, 0xbe, 0x9a, 0x4b, 0xee, 0xd2, 0x70, 0x19, 0x3d, 0x7a, 0x0f, 0x92, 0x43,
	0xd0, 0x0c, 0xe9, 0x00, 0x3a, 0x54, 0x0d, 0xed, 0x5c, 0xc9, 0x2a, 0x17, 0xc8, 0xaa, 0x8c, 0x9f,
	0x23, 0x34, 0x95, 0xaa, 0x72, 0x10, 0xdb, 0x9b, 0x26, 0x28, 0xa3, 0xe0, 0x8f, 0x08, 0xb5, 0xa8,
	0x37, 0x64, 0x1c, 0xea, 0xfd, 0x81, 0xbd, 0x65, 0xce, 0xf8, 0x7a, 0x8d, 0x2a, 0xe7, 0x49, 0xc6,
	0xaa, 0x44, 0x52, 0x7d, 0x74, 0x92, 0x41, 0xe1, 0x33, 0x54, 0x20, 0x42, 0xa8, 0x86, 0x64, 0x63,
	0xb0, 0xb7, 0x0d, 0xb7, 0xbc, 0x06, 0xd7, 0xc4, 0x93, 0x34, 0x15, 0x77, 0xd1, 0x5e, 0xd5, 0xf7,
	0x99, 0xe6, 0xd3, 0xc0, 0x48, 0xb1, 0xfd, 0xc0, 0x98, 0xb9, 0x3e, 0xee, 0x0e, 0x01, 0x9f, 0xa0,
	0xa7, 0x77, 0x2d, 0xbf, 0xa4, 0x21, 0xc4, 0x11, 0xf5, 0xc0, 0xce, 0x1b, 0x9f, 0x7e, 0x17, 0xe2,
	0x7c, 0xdf, 0xb8, 0x0f, 0xb1, 0xe8, 0x91, 0x36, 0xbe, 0x45, 0xbd, 0xaa, 0xef, 0x4b, 0x88, 0xa7,
	0xc3, 0x53, 0x20, 0x19, 0x05, 0x97, 0x50, 0xf1, 0x5c, 0xc4, 0xaa, 0x01, 0x63, 0xcd, 0x34, 0xb3,
	0x5a, 0x20, 0x59, 0x09, 0x3f, 0x43, 0x85, 0x6a, 0x10, 0x88, 0x9b, 0x56, 0xab, 0x71, 0x65, 0xda,
	0x9b, 0x27, 0xa9, 0x80, 0xbb, 0x68, 0xb7, 0xc9, 0x09, 0x55, 0x70, 0xc1, 0x42, 0xa6, 0x40, 0x9a,
	0xde, 0x16, 0x8f, 0xdc, 0x35, 0x4c, 0xc9, 0x64, 0x91, 0x65, 0x08, 0xbe, 0x46, 0x0f, 0xdb, 0x89,
	0xca, 0x62, 0xb7, 0xfe, 0x09, 0xbb, 0x42, 0x71, 0xbe, 0x5a, 0xe8, 0xc5, 0x1f, 0xa6, 0x47, 0x3b,
	0x52, 0xef, 0x7c, 0xe8, 0x42, 0x18, 0x05, 0x54, 0xc1, 0xcc, 0xb2, 0xac, 0xa4, 0x1d, 0x39, 0x57,
	0xa7, 0x9c, 0xf6, 0x02, 0xf0, 0x8d, 0x63, 0x79, 0x92, 0x0a, 0xc6, 0x71, 0x08, 0xaf, 0xd8, 0x17,
	0x68, 0xb1, 0x9e, 0x31, 0x6c, 0x97, 0x64, 0x14, 0x9d, 0x7d, 0xed, 0x45, 0x49, 0x5d, 0x24, 0x5c,
	0x19, 0xb7, 0x76, 0x49, 0x2a, 0x38, 0x3f, 0x2d, 0xb4, 0xb7, 0x3a, 0x38, 0x1a, 0xd9, 0x8c, 0x09,
	0x50, 0xbf, 0xcd, 0x83, 0x89, 0xa9, 0x28, 0x4f, 0x32, 0x0a, 0x76, 0xd0, 0x4e, 0x33, 0x36, 0xb3,
	0x0a, 0x63, 0xe6, 0xc1, 0xac, 0xa6, 0x25, 0x4d, 0x3f, 0x58, 0x1d, 0x2a, 0x55, 0x92, 0x30, 0x7f,
	0x76, 0x49, 0x17, 0x6b, 0xcd, 0xd7, 0xb7, 0xb4, 0xcd, 0x75, 0xdf, 0xe7, 0xb7, 0x33, 0x55, 0x70,
	0x07, 0x15, 0xff, 0xbf, 0x17, 0x59, 0x84, 0xf3, 0xcd, 0x42, 0x07, 0xf7, 0xc7, 0xe1, 0x0b, 0x54,
	0xa8, 0x51, 0xee, 0xdf, 0x30, 0x5f, 0x0d, 0x67, 0xaf, 0xdd, 0x3a, 0x5b, 0x75, 0xc5, 0x08, 0x78,
	0x2d, 0xf1, 0x46, 0xa0, 0x48, 0x0a, 0xc0, 0x27, 0x28, 0xd7, 0x8e, 0xe6, 0x6f, 0xf0, 0xdf, 0x72,
	0x74, 0xaa, 0x73, 0xbb, 0x54, 0x69, 0xe6, 0x67, 0x6d, 0x7b, 0x9b, 0x43, 0x97, 0x85, 0x50, 0x4b,
	0x64, 0xac, 0x4c, 0xb1, 0x39, 0xb2, 0xa4, 0x69, 0x6b, 0x09, 0xf4, 0x59, 0x10, 0x68, 0xc9, 0x94,
	0x91, 0x23, 0x19, 0x45, 0xb7, 0xa5, 0x4e, 0x23, 0xea, 0x31, 0x35, 0x31, 0x6d, 0xc9, 0x91, 0xc5,
	0xba, 0xf6, 0xf6, 0xd3, 0x9b, 0x01, 0x53, 0xc3, 0xa4, 0xe7, 0x7a, 0x22, 0xac, 0x64, 0x4a, 0x7f,
	0x19, 0x32, 0x4f, 0x8a, 0xf1, 0xb2, 0x96, 0x1e, 0x67, 0xf6, 0xe7, 0xb5, 0x6d, 0x3e, 0x8e, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x4c, 0xce, 0xa7, 0xfe, 0x06, 0x00, 0x00,
}
