// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fccontrol.proto

package fccontrol

import (
	context "context"
	fmt "fmt"
	github_com_containerd_ttrpc "github.com/containerd/ttrpc"
	proto1 "github.com/firecracker-microvm/firecracker-containerd/proto"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("fccontrol.proto", fileDescriptor_b99f53e2bf82c5ef) }

var fileDescriptor_b99f53e2bf82c5ef = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x1b, 0x09, 0x95, 0xd6, 0xa8, 0xb4, 0xb5, 0x00, 0xa1, 0x02, 0x5e, 0xd8, 0x5d, 0x54,
	0x98, 0x3b, 0x40, 0xa1, 0xea, 0x10, 0x09, 0x35, 0x22, 0x03, 0x9b, 0xe3, 0x5e, 0xaa, 0x8a, 0x36,
	0x0e, 0xb6, 0x33, 0xb0, 0xf1, 0x3a, 0xbc, 0x49, 0x47, 0x46, 0x46, 0x9a, 0x27, 0x41, 0xf9, 0xe3,
	0x50, 0xa2, 0xa2, 0x6c, 0x9f, 0x7f, 0xf6, 0x7d, 0xf7, 0xdd, 0xc9, 0xa8, 0xed, 0x73, 0x2e, 0x02,
	0x2d, 0xc5, 0x92, 0x86, 0x52, 0x68, 0xd1, 0x3b, 0x9b, 0x0b, 0x31, 0x5f, 0x42, 0x3f, 0x3d, 0x79,
	0x91, 0xdf, 0x87, 0x55, 0xa8, 0xdf, 0xf2, 0xcb, 0xae, 0xbf, 0x90, 0xc0, 0x25, 0xe3, 0x2f, 0x20,
	0x33, 0x34, 0xf8, 0xd8, 0x43, 0x07, 0x0f, 0xbf, 0x14, 0xf7, 0x51, 0xe3, 0x4e, 0x02, 0xd3, 0xe0,
	0xda, 0xb8, 0x43, 0x8d, 0x9c, 0xc2, 0x6b, 0x04, 0x4a, 0xf7, 0xba, 0x5b, 0x44, 0x85, 0x22, 0x50,
	0x80, 0x07, 0x68, 0xff, 0x91, 0x45, 0x2a, 0x79, 0xdf, 0xa6, 0xb9, 0x32, 0xcf, 0x4f, 0x68, 0x96,
	0x86, 0x9a, 0x34, 0xf4, 0x3e, 0x49, 0x83, 0x6f, 0x50, 0x63, 0x0a, 0x2a, 0x5a, 0x65, 0x4d, 0x8c,
	0xac, 0xaa, 0xba, 0x42, 0x75, 0x47, 0x8b, 0xd0, 0xb5, 0xf1, 0x21, 0xcd, 0x44, 0x55, 0xc5, 0x00,
	0x35, 0xc7, 0xa0, 0x5d, 0x7b, 0x12, 0xf8, 0x02, 0x77, 0x69, 0xa1, 0x4d, 0x1d, 0xde, 0x46, 0xf9,
	0x3c, 0x43, 0xd4, 0x72, 0x12, 0x68, 0x83, 0x66, 0x33, 0xa6, 0x19, 0x3e, 0xa6, 0x7f, 0xce, 0x55,
	0x3d, 0x47, 0xa8, 0xf3, 0x14, 0xce, 0xd2, 0x1d, 0x15, 0x16, 0xa7, 0xb4, 0x8c, 0xaa, 0x5c, 0x86,
	0xa8, 0x35, 0x2e, 0xa5, 0x18, 0xef, 0x4e, 0x51, 0xc2, 0xf9, 0x14, 0x0e, 0x3a, 0x1a, 0x81, 0xe2,
	0x72, 0xe1, 0xc1, 0x24, 0x50, 0x9a, 0x05, 0x1c, 0xd2, 0x25, 0x9c, 0xd3, 0x5d, 0xd8, 0xb8, 0x5d,
	0xfc, 0x73, 0x9b, 0x99, 0xde, 0x5e, 0xae, 0x37, 0xa4, 0xf6, 0xb5, 0x21, 0xb5, 0xf7, 0x98, 0x58,
	0xeb, 0x98, 0x58, 0x9f, 0x31, 0xb1, 0xbe, 0x63, 0x62, 0x3d, 0x37, 0x8b, 0x6f, 0xe8, 0xd5, 0xd3,
	0x49, 0xae, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x39, 0xfa, 0x43, 0x9a, 0x02, 0x00, 0x00,
}

type FirecrackerService interface {
	CreateVM(ctx context.Context, req *proto1.CreateVMRequest) (*proto1.CreateVMResponse, error)
	PauseVM(ctx context.Context, req *proto1.PauseVMRequest) (*empty.Empty, error)
	ResumeVM(ctx context.Context, req *proto1.ResumeVMRequest) (*empty.Empty, error)
	StopVM(ctx context.Context, req *proto1.StopVMRequest) (*empty.Empty, error)
	GetVMInfo(ctx context.Context, req *proto1.GetVMInfoRequest) (*proto1.GetVMInfoResponse, error)
	SetVMMetadata(ctx context.Context, req *proto1.SetVMMetadataRequest) (*empty.Empty, error)
	UpdateVMMetadata(ctx context.Context, req *proto1.UpdateVMMetadataRequest) (*empty.Empty, error)
	GetVMMetadata(ctx context.Context, req *proto1.GetVMMetadataRequest) (*proto1.GetVMMetadataResponse, error)
	DescribeInstanceInfo(ctx context.Context, req *proto1.DescribeInstanceInfoRequest) (*proto1.DescribeInstanceInfoResponse, error)
}

func RegisterFirecrackerService(srv *github_com_containerd_ttrpc.Server, svc FirecrackerService) {
	srv.Register("Firecracker", map[string]github_com_containerd_ttrpc.Method{
		"CreateVM": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.CreateVMRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.CreateVM(ctx, &req)
		},
		"PauseVM": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.PauseVMRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.PauseVM(ctx, &req)
		},
		"ResumeVM": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.ResumeVMRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.ResumeVM(ctx, &req)
		},
		"StopVM": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.StopVMRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.StopVM(ctx, &req)
		},
		"GetVMInfo": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.GetVMInfoRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.GetVMInfo(ctx, &req)
		},
		"SetVMMetadata": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.SetVMMetadataRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.SetVMMetadata(ctx, &req)
		},
		"UpdateVMMetadata": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.UpdateVMMetadataRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.UpdateVMMetadata(ctx, &req)
		},
		"GetVMMetadata": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.GetVMMetadataRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.GetVMMetadata(ctx, &req)
		},
		"DescribeInstanceInfo": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req proto1.DescribeInstanceInfoRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.DescribeInstanceInfo(ctx, &req)
		},
	})
}

type firecrackerClient struct {
	client *github_com_containerd_ttrpc.Client
}

func NewFirecrackerClient(client *github_com_containerd_ttrpc.Client) FirecrackerService {
	return &firecrackerClient{
		client: client,
	}
}

func (c *firecrackerClient) CreateVM(ctx context.Context, req *proto1.CreateVMRequest) (*proto1.CreateVMResponse, error) {
	var resp proto1.CreateVMResponse
	if err := c.client.Call(ctx, "Firecracker", "CreateVM", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) PauseVM(ctx context.Context, req *proto1.PauseVMRequest) (*empty.Empty, error) {
	var resp empty.Empty
	if err := c.client.Call(ctx, "Firecracker", "PauseVM", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) ResumeVM(ctx context.Context, req *proto1.ResumeVMRequest) (*empty.Empty, error) {
	var resp empty.Empty
	if err := c.client.Call(ctx, "Firecracker", "ResumeVM", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) StopVM(ctx context.Context, req *proto1.StopVMRequest) (*empty.Empty, error) {
	var resp empty.Empty
	if err := c.client.Call(ctx, "Firecracker", "StopVM", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) GetVMInfo(ctx context.Context, req *proto1.GetVMInfoRequest) (*proto1.GetVMInfoResponse, error) {
	var resp proto1.GetVMInfoResponse
	if err := c.client.Call(ctx, "Firecracker", "GetVMInfo", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) SetVMMetadata(ctx context.Context, req *proto1.SetVMMetadataRequest) (*empty.Empty, error) {
	var resp empty.Empty
	if err := c.client.Call(ctx, "Firecracker", "SetVMMetadata", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) UpdateVMMetadata(ctx context.Context, req *proto1.UpdateVMMetadataRequest) (*empty.Empty, error) {
	var resp empty.Empty
	if err := c.client.Call(ctx, "Firecracker", "UpdateVMMetadata", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) GetVMMetadata(ctx context.Context, req *proto1.GetVMMetadataRequest) (*proto1.GetVMMetadataResponse, error) {
	var resp proto1.GetVMMetadataResponse
	if err := c.client.Call(ctx, "Firecracker", "GetVMMetadata", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *firecrackerClient) DescribeInstanceInfo(ctx context.Context, req *proto1.DescribeInstanceInfoRequest) (*proto1.DescribeInstanceInfoResponse, error) {
	var resp proto1.DescribeInstanceInfoResponse
	if err := c.client.Call(ctx, "Firecracker", "DescribeInstanceInfo", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
