name: firecracker-containerd
summary: container runtime.
description: firecracker-containerd enables containerd to manage containers as Firecracker microVMs .
  
adopt-info: firecracker-containerd

grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  firecracker-containerd:
    command: bin/firecracker-containerd
    plugs:
      - docker
      - home
      - network
      - removable-media

parts:
  firecracker-containerd:
plugin: nil 
    source: https://github.com/firecracker-microvm/firecracker-containerd.git
    source-type: git
    override-pull: |
      git clone https://github.com/firecracker-microvm/firecracker-containerd.git src/github.com/firecracker-microvm/firecracker-containerd
       cd src/github.com/firecracker-microvm/firecracker-containerd
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/firecracker-microvm/firecracker-containerd
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/firecracker-microvm/firecracker-containerd/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/firecracker-microvm/firecracker-containerd/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/drone
    build-snaps:
      - go
    build-packages:
      - git
      - sed


